/**
 * Environment Step
 *
 * Creates or updates the .env configuration file.
 */

import crypto from "crypto";
import type { ISetupStep, StepResult, SetupContext } from "./step.interface";

export class EnvironmentStep implements ISetupStep {
  readonly id = "environment";
  readonly name = "Setup environment";
  readonly order = 20;
  readonly skippable = false;

  async execute(context: SetupContext): Promise<StepResult> {
    const envPath = context.filesystem.join(context.projectRoot, ".env");
    const envExists = await context.filesystem.pathExists(envPath);

    // Check if we should overwrite
    if (envExists) {
      if (context.options.nonInteractive) {
        return {
          success: true,
          message: "Keeping existing .env file",
          skipReason: "File already exists",
        };
      }

      const overwrite = await context.prompts.confirm(
        ".env file already exists. Overwrite?",
        false
      );

      if (!overwrite) {
        return {
          success: true,
          message: "Keeping existing .env file",
          skipReason: "User chose not to overwrite",
        };
      }
    }

    // Generate configuration
    context.output.startSpinner("Creating environment configuration...");

    const jwtSecret = crypto.randomBytes(32).toString("hex");
    const envContent = this.generateEnvContent(jwtSecret);

    await context.filesystem.writeFile(envPath, envContent);

    context.output.succeedSpinner("Environment configured");
    context.output.dim(`  Created: ${envPath}`);

    return {
      success: true,
      message: "Environment configuration created",
    };
  }

  private generateEnvContent(jwtSecret: string): string {
    return `# Clawster Environment Configuration
# Generated by 'clawster setup' on ${new Date().toISOString()}

# Database (path relative to packages/database/prisma/)
DATABASE_URL=file:./dev.db

# Authentication
JWT_SECRET=${jwtSecret}

# API Server
PORT=4000
DEFAULT_DEPLOYMENT_TARGET=docker

# Frontend
NEXT_PUBLIC_API_URL=http://localhost:4000

# AWS (optional - needed for cloud deployments)
# AWS_REGION=us-east-1
# AWS_ACCESS_KEY_ID=
# AWS_SECRET_ACCESS_KEY=
# AWS_ACCOUNT_ID=

# ECS (optional - populated by 'clawster init')
# ECS_CLUSTER_ARN=
# ECS_EXECUTION_ROLE_ARN=
# ECS_TASK_ROLE_ARN=
# PRIVATE_SUBNET_IDS=
# SECURITY_GROUP_ID=
`;
  }
}
